In [1]:
import pandas as pd

In [2]:
import pandas as pd
infos_path = "./data/20220920毒性与组分副本.xlsx"

In [3]:
infos = pd.read_excel(infos_path,index_col="组分")

In [4]:
infos.head(2)

,25 µg/mL(哈尔滨-优),50 µg/mL(哈尔滨-优),100 µg/mL(哈尔滨-优),200 µg/mL(哈尔滨-优),25 µg/mL(哈尔滨-轻污（非供),50 µg/mL(哈尔滨-轻污（非供）),100 µg/mL(哈尔滨-轻污（非供),200 µg/mL(哈尔滨-轻污（非供）),25 µg/mL(哈尔滨-轻污（供暖）),50 µg/mL(哈尔滨-轻污（供暖）),...,100 µg/mL(哈尔滨-严重),200 µg/mL(哈尔滨-严重),25 µg/mL(杭州-优),50 µg/mL(杭州-优),100 µg/mL(杭州-优),200 µg/mL(杭州-优),25 µg/mL(杭州-重污),50 µg/mL(杭州-重污),100 µg/mL(杭州-重污),200 µg/mL(杭州-重污)
组分,,,,,,,,,,,,,,,,,,,,,
Na+,3.992286,7.984571,15.969143,31.938286,2.574212,5.148423,10.296846,20.593692,1.841000,3.682000,...,5.932964,11.865929,4.452583,8.905167,17.810333,35.620667,2.182043,4.364085,8.728170,17.456340
NH4+,0.239333,0.478667,0.957333,1.914667,0.484231,0.968462,1.936923,3.873846,0.679404,1.358808,...,4.219214,8.438429,0.431792,0.863583,1.727167,3.454333,1.785766,3.571532,7.143064,14.286128

In [5]:
trans_infos = infos.T

In [6]:
trans_infos.head(2)

组分,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Hg,Tl,Pb,Na,Mg,Al,K,Ca,Fe,WSOC
25 µg/mL(哈尔滨-优),3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.000007,0.0,0.000047,8.804629,0.086694,0.008831,0.289312,0.329025,0.001763,3.0
50 µg/mL(哈尔滨-优),7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.000014,0.0,0.000093,17.609258,0.173388,0.017663,0.578624,0.658051,0.003527,6.0

In [43]:
trans_infos["Be"]

25 µg/mL(哈尔滨-优)          0.000000
50 µg/mL(哈尔滨-优)          0.000000
100 µg/mL(哈尔滨-优)         0.000000
200 µg/mL(哈尔滨-优)         0.000000
25 µg/mL(哈尔滨-轻污（非供)      0.000000
50 µg/mL(哈尔滨-轻污（非供）)     0.000000
100 µg/mL(哈尔滨-轻污（非供)     0.000000
200 µg/mL(哈尔滨-轻污（非供）)    0.000000
25 µg/mL(哈尔滨-轻污（供暖）)     0.000000
50 µg/mL(哈尔滨-轻污（供暖）)     0.000000
100 µg/mL(哈尔滨-轻污（供暖）)    0.000000
200 µg/mL(哈尔滨-轻污（供暖）)    0.000000
25 µg/mL(哈尔滨-重污)         0.000001
50 µg/mL(哈尔滨-重污)         0.000003
100 µg/mL(哈尔滨-重污)        0.000006
200 µg/mL(哈尔滨-重污)        0.000011
25 µg/mL(哈尔滨-严重)         0.000000
50 µg/mL(哈尔滨-严重)         0.000000
100 µg/mL(哈尔滨-严重)        0.000000
200 µg/mL(哈尔滨-严重)        0.000000
25 µg/mL(杭州-优)           0.000000
50 µg/mL(杭州-优)           0.000000
100 µg/mL(杭州-优)          0.000000
200 µg/mL(杭州-优)          0.000000
25 µg/mL(杭州-重污)          0.000000
50 µg/mL(杭州-重污)          0.000000
100 µg/mL(杭州-重污)         0.000000
200 µg/mL(杭州-重污)         0.000000
Name: Be, dtype: float64

In [22]:
trans_infos.to_excel("./data/toxic_ingredient.xlsx")

In [8]:
toxic_path = "./data/Toxic.xlsx"

In [10]:
toxic_infos = pd.read_excel(toxic_path,index_col="组分")

In [11]:
trans_toxic_infos  = toxic_infos.T

In [12]:
trans_toxic_infos.head(2)

组分,心包水肿,心律异常,血流过慢,循环缺失,出血及血栓,畸形,短小,眼变小,缺失,肝变小,肝变性,卵黄囊吸收延迟,水肿,肠腔异常,弯曲,肌肉变性,异常,体长变短,死亡
25 µg/mL(哈尔滨-优),0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）
50 µg/mL(哈尔滨-优),0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）

In [13]:
trans_infos["Be"]

25 µg/mL(哈尔滨-优)          0.000000
50 µg/mL(哈尔滨-优)          0.000000
100 µg/mL(哈尔滨-优)         0.000000
200 µg/mL(哈尔滨-优)         0.000000
25 µg/mL(哈尔滨-轻污（非供)      0.000000
50 µg/mL(哈尔滨-轻污（非供）)     0.000000
100 µg/mL(哈尔滨-轻污（非供)     0.000000
200 µg/mL(哈尔滨-轻污（非供）)    0.000000
25 µg/mL(哈尔滨-轻污（供暖）)     0.000000
50 µg/mL(哈尔滨-轻污（供暖）)     0.000000
100 µg/mL(哈尔滨-轻污（供暖）)    0.000000
200 µg/mL(哈尔滨-轻污（供暖）)    0.000000
25 µg/mL(哈尔滨-重污)         0.000001
50 µg/mL(哈尔滨-重污)         0.000003
100 µg/mL(哈尔滨-重污)        0.000006
200 µg/mL(哈尔滨-重污)        0.000011
25 µg/mL(哈尔滨-严重)         0.000000
50 µg/mL(哈尔滨-严重)         0.000000
100 µg/mL(哈尔滨-严重)        0.000000
200 µg/mL(哈尔滨-严重)        0.000000
25 µg/mL(杭州-优)           0.000000
50 µg/mL(杭州-优)           0.000000
100 µg/mL(杭州-优)          0.000000
200 µg/mL(杭州-优)          0.000000
25 µg/mL(杭州-重污)          0.000000
50 µg/mL(杭州-重污)          0.000000
100 µg/mL(杭州-重污)         0.000000
200 µg/mL(杭州-重污)         0.000000
Name: Be, dtype: float64

In [38]:
toxic_ingredient_path = "./data/toxic_ingredient.xlsx"
ingredient_infos = pd.read_excel(toxic_ingredient_path)

In [40]:
ingredient_infos["Be"]

0     0.000000
1     0.000000
2     0.000000
3     0.000000
4     0.000000
5     0.000000
6     0.000000
7     0.000000
8     0.000000
9     0.000000
10    0.000000
11    0.000000
12    0.000001
13    0.000003
14    0.000006
15    0.000011
16    0.000000
17    0.000000
18    0.000000
19    0.000000
20    0.000000
21    0.000000
22    0.000000
23    0.000000
24    0.000000
25    0.000000
26    0.000000
27    0.000000
Name: Be, dtype: float64

In [14]:
ingredient_path = "./data/toxic_ingredient.xlsx"
ingredient_infos = pd.read_excel(ingredient_path)

In [15]:
ingredient_infos.head(2)

,degree,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,...,Hg,Tl,Pb,Na,Mg,Al,K,Ca,Fe,WSOC
0,25 µg/mL(哈尔滨-优),3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,...,0.000007,0.0,0.000047,8.804629,0.086694,0.008831,0.289312,0.329025,0.001763,3.0
1,50 µg/mL(哈尔滨-优),7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,...,0.000014,0.0,0.000093,17.609258,0.173388,0.017663,0.578624,0.658051,0.003527,6.0

In [17]:
degree_path = "./data/toxic_degree.xlsx"
degree_infos = pd.read_excel(degree_path)

In [18]:
degree_infos.head(2)

,degree,心包水肿,心律异常,血流过慢,循环缺失,出血及血栓,畸形,短小,眼变小,缺失,肝变小,肝变性,卵黄囊吸收延迟,水肿,肠腔异常,弯曲,肌肉变性,异常,体长变短,死亡
0,25 µg/mL(哈尔滨-优),0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）
1,50 µg/mL(哈尔滨-优),0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）

In [19]:
infos = pd.merge(ingredient_infos,degree_infos,on="degree")

In [20]:
infos.head(2)

,degree,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,...,肝变小,肝变性,卵黄囊吸收延迟,水肿,肠腔异常,弯曲,肌肉变性,异常,体长变短,死亡
0,25 µg/mL(哈尔滨-优),3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,...,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）
1,50 µg/mL(哈尔滨-优),7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,...,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）

In [21]:
infos.to_excel("./data/ingredient_degree.xlsx")

In [22]:
import pandas as pd
import numpy as np

In [23]:
infos_path = "./data/ingredient_degree.xlsx"
infos = pd.read_excel(infos_path)

In [24]:
infos.head(2)

,Unnamed: 0,degree,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,...,肝变小,肝变性,卵黄囊吸收延迟,水肿,肠腔异常,弯曲,肌肉变性,异常,体长变短,死亡
0,0,25 µg/mL(哈尔滨-优),3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,...,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）
1,1,50 µg/mL(哈尔滨-优),7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,...,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）,0%（0/30）

In [27]:
columns = infos.columns.to_list()
columns[:5]

['Unnamed: 0', 'degree', 'Na+', 'NH4+', 'K+']

In [28]:
index = columns[2:36]
index[:5]

['Na+', 'NH4+', 'K+', 'Mg2+', 'Ca2+']

In [29]:
pericadium_infos = infos[index]
pericadium_infos.head(2)

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Hg,Tl,Pb,Na,Mg,Al,K,Ca,Fe,WSOC
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.000007,0.0,0.000047,8.804629,0.086694,0.008831,0.289312,0.329025,0.001763,3.0
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.000014,0.0,0.000093,17.609258,0.173388,0.017663,0.578624,0.658051,0.003527,6.0

In [30]:
pericadium_infos["Na-Na+"] = pericadium_infos["Na"]-pericadium_infos["Na+"]
pericadium_infos["K-K+"] = pericadium_infos["K"]-pericadium_infos["K+"]
pericadium_infos["Ca-Ca2+"] = pericadium_infos["Ca"]-pericadium_infos["Ca2+"]
pericadium_infos["Mg-Mg2+"] = pericadium_infos["Mg"]-pericadium_infos["Mg2+"]
pericadium_infos.head(2)

/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Mg,Al,K,Ca,Fe,WSOC,Na-Na+,K-K+,Ca-Ca2+,Mg-Mg2+
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.086694,0.008831,0.289312,0.329025,0.001763,3.0,4.812343,0.031145,0.068716,0.034266
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.173388,0.017663,0.578624,0.658051,0.003527,6.0,9.624687,0.062290,0.137432,0.068531

In [31]:
infos["label_num"] = [num.split("（")[0] for num in infos["循环缺失"].values]

infos["label_num"]= infos["label_num"].str.strip("%").astype(float)/100

In [32]:
pericadium_infos.head(2)

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Mg,Al,K,Ca,Fe,WSOC,Na-Na+,K-K+,Ca-Ca2+,Mg-Mg2+
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.086694,0.008831,0.289312,0.329025,0.001763,3.0,4.812343,0.031145,0.068716,0.034266
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.173388,0.017663,0.578624,0.658051,0.003527,6.0,9.624687,0.062290,0.137432,0.068531

In [33]:
category_ls = []
for num in infos["label_num"]:
    if num == 0:
        category_ls.append(0)
    elif num >0 and num <= 0.333:
        category_ls.append(1)
    elif num > 0.33 and num <=0.666:
        category_ls.append(2)
    else:
        category_ls.append(3)
pericadium_infos["label"] = category_ls

/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()

In [34]:
pericadium_infos.head(2)

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Al,K,Ca,Fe,WSOC,Na-Na+,K-K+,Ca-Ca2+,Mg-Mg2+,label
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.008831,0.289312,0.329025,0.001763,3.0,4.812343,0.031145,0.068716,0.034266,0
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.017663,0.578624,0.658051,0.003527,6.0,9.624687,0.062290,0.137432,0.068531,0

In [177]:
pericadium_infos.to_excel("./data/sub_data/cycle_defeat_infos.xlsx")

In [ ]:
### Data Index analysis
### The related analysis among indexs

In [35]:
import pandas as pd

In [37]:
infos_path = "./data/sub_data/cycle_defeat_infos.xlsx"
infos = pd.read_excel(infos_path)
infos.head(2)

,Unnamed: 0,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,...,Tl,Pb,Na,Mg,Al,K,Ca,Fe,WSOC,label
0,0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,...,0.0,0.000047,8.804629,0.086694,0.008831,0.289312,0.329025,0.001763,3.0,0
1,1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,...,0.0,0.000093,17.609258,0.173388,0.017663,0.578624,0.658051,0.003527,6.0,0

In [38]:
index_names = infos.columns.to_list()
len(index_names)

36

In [39]:
indexs = index_names[1:35]
indexs
indexs.remove("Co")

In [41]:
processInfos_x = infos[indexs]
Infos_target = infos["label"]
processInfos_x.head(2)

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Hg,Tl,Pb,Na,Mg,Al,K,Ca,Fe,WSOC
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.000007,0.0,0.000047,8.804629,0.086694,0.008831,0.289312,0.329025,0.001763,3.0
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.000014,0.0,0.000093,17.609258,0.173388,0.017663,0.578624,0.658051,0.003527,6.0

In [42]:
from sklearn.feature_selection import VarianceThreshold
thresholder = VarianceThreshold(threshold=.0000001)
feature_high_variance = thresholder.fit_transform(processInfos_x)
feature_high_variance.T
#thresholder.fit(processInfos_x).variances_

array([[3.99228571e+00, 7.98457143e+00, 1.59691429e+01, 3.19382857e+01,
        2.57421154e+00, 5.14842308e+00, 1.02968462e+01, 2.05936923e+01,
        1.84100000e+00, 3.68200000e+00, 7.36400000e+00, 1.47280000e+01,
        2.71251429e+00, 5.42502857e+00, 1.08500571e+01, 2.17001143e+01,
        1.48324107e+00, 2.96648214e+00, 5.93296429e+00, 1.18659286e+01,
        4.45258333e+00, 8.90516667e+00, 1.78103333e+01, 3.56206667e+01,
        2.18204255e+00, 4.36408511e+00, 8.72817021e+00, 1.74563404e+01],
       [2.39333333e-01, 4.78666667e-01, 9.57333333e-01, 1.91466667e+00,
        4.84230769e-01, 9.68461538e-01, 1.93692308e+00, 3.87384615e+00,
        6.79403846e-01, 1.35880769e+00, 2.71761538e+00, 5.43523077e+00,
        1.14781429e+00, 2.29562857e+00, 4.59125714e+00, 9.18251429e+00,
        1.05480357e+00, 2.10960714e+00, 4.21921429e+00, 8.43842857e+00,
        4.31791667e-01, 8.63583333e-01, 1.72716667e+00, 3.45433333e+00,
        1.78576596e+00, 3.57153191e+00, 7.14306383e+00, 1.42861277e+01],
       [2.58166667e-01, 5.16333333e-01, 1.03266667e+00, 2.06533333e+00,
        3.73826923e-01, 7.47653846e-01, 1.49530769e+00, 2.99061538e+00,
        4.61673077e-01, 9.23346154e-01, 1.84669231e+00, 3.69338462e+00,
        5.85485714e-01, 1.17097143e+00, 2.34194286e+00, 4.68388571e+00,
        8.03910714e-01, 1.60782143e+00, 3.21564286e+00, 6.43128571e+00,
        2.23020833e-01, 4.46041667e-01, 8.92083333e-01, 1.78416667e+00,
        4.13356383e-01, 8.26712766e-01, 1.65342553e+00, 3.30685106e+00],
       [5.24285714e-02, 1.04857143e-01, 2.09714286e-01, 4.19428571e-01,
        7.32500000e-02, 1.46500000e-01, 2.93000000e-01, 5.86000000e-01,
        7.59615385e-02, 1.51923077e-01, 3.03846154e-01, 6.07692308e-01,
        5.70285714e-02, 1.14057143e-01, 2.28114286e-01, 4.56228571e-01,
        5.80714286e-02, 1.16142857e-01, 2.32285714e-01, 4.64571429e-01,
        4.91875000e-02, 9.83750000e-02, 1.96750000e-01, 3.93500000e-01,
        6.41063830e-02, 1.28212766e-01, 2.56425532e-01, 5.12851064e-01],
       [2.60309524e-01, 5.20619048e-01, 1.04123810e+00, 2.08247619e+00,
        5.45096154e-01, 1.09019231e+00, 2.18038462e+00, 4.36076923e+00,
        6.57884615e-01, 1.31576923e+00, 2.63153846e+00, 5.26307692e+00,
        3.36957143e-01, 6.73914286e-01, 1.34782857e+00, 2.69565714e+00,
        5.75464286e-01, 1.15092857e+00, 2.30185714e+00, 4.60371429e+00,
        2.32770833e-01, 4.65541667e-01, 9.31083333e-01, 1.86216667e+00,
        7.42372340e-01, 1.48474468e+00, 2.96948936e+00, 5.93897872e+00],
       [1.50952381e-02, 3.01904762e-02, 6.03809524e-02, 1.20761905e-01,
        1.30384615e-02, 2.60769231e-02, 5.21538462e-02, 1.04307692e-01,
        2.51346154e-02, 5.02692308e-02, 1.00538462e-01, 2.01076923e-01,
        4.54142857e-02, 9.08285714e-02, 1.81657143e-01, 3.63314286e-01,
        4.56517857e-02, 9.13035714e-02, 1.82607143e-01, 3.65214286e-01,
        8.83333333e-03, 1.76666667e-02, 3.53333333e-02, 7.06666667e-02,
        8.84574468e-03, 1.76914894e-02, 3.53829787e-02, 7.07659574e-02],
       [6.63261905e-01, 1.32652381e+00, 2.65304762e+00, 5.30609524e+00,
        1.01803846e+00, 2.03607692e+00, 4.07215385e+00, 8.14430769e+00,
        1.68844231e+00, 3.37688462e+00, 6.75376923e+00, 1.35075385e+01,
        2.02695714e+00, 4.05391429e+00, 8.10782857e+00, 1.62156571e+01,
        3.26308929e+00, 6.52617857e+00, 1.30523571e+01, 2.61047143e+01,
        7.35958333e-01, 1.47191667e+00, 2.94383333e+00, 5.88766667e+00,
        1.35285106e+00, 2.70570213e+00, 5.41140426e+00, 1.08228085e+01],
       [1.87635714e+00, 3.75271429e+00, 7.50542857e+00, 1.50108571e+01,
        2.24021154e+00, 4.48042308e+00, 8.96084615e+00, 1.79216923e+01,
        1.23717308e+00, 2.47434615e+00, 4.94869231e+00, 9.89738462e+00,
        3.09411429e+00, 6.18822857e+00, 1.23764571e+01, 2.47529143e+01,
        2.26344643e+00, 4.52689286e+00, 9.05378571e+00, 1.81075714e+01,
        3.30835417e+00, 6.61670833e+00, 1.32334167e+01, 2.64668333e+01,
        1.14765372e+01, 2.29530745e+01, 4.59061489e+01, 9.18122979e+01],
       [6.11000000e+00, 1.22200000e+01, 2.44400000e+01, 4.88800000e+01,
        3.93221154e+00, 7.86442308e+00, 1.57288462e+01, 3.14576923e+01,
        3.73276923e+00, 7.46553846e+00, 1.49310769e+01, 2.98621538e+01,
        5.09132857e+00, 1.01826571e+01, 2.03653143e+01, 4.07306286e+01,
        3.59160714e+00, 7.18321429e+00, 1.43664286e+01, 2.87328571e+01,
        6.13614583e+00, 1.22722917e+01, 2.45445833e+01, 4.90891667e+01,
        7.93129787e+00, 1.58625957e+01, 3.17251915e+01, 6.34503830e+01],
       [5.02521289e-04, 1.00504258e-03, 2.01008515e-03, 4.02017031e-03,
        3.44793221e-04, 6.89586441e-04, 1.37917288e-03, 2.75834576e-03,
        2.70405218e-04, 5.40810435e-04, 1.08162087e-03, 2.16324174e-03,
        4.33782588e-04, 8.67565177e-04, 1.73513035e-03, 3.47026071e-03,
        2.92504548e-04, 5.85009095e-04, 1.17001819e-03, 2.34003638e-03,
        7.18543470e-04, 1.43708694e-03, 2.87417388e-03, 5.74834776e-03,
        5.96048227e-04, 1.19209645e-03, 2.38419291e-03, 4.76838582e-03],
       [4.97762159e-04, 9.95524318e-04, 1.99104864e-03, 3.98209727e-03,
        3.57286162e-04, 7.14572324e-04, 1.42914465e-03, 2.85828929e-03,
        2.25922180e-04, 4.51844359e-04, 9.03688718e-04, 1.80737744e-03,
        7.05142171e-04, 1.41028434e-03, 2.82056869e-03, 5.64113737e-03,
        4.85428579e-04, 9.70857158e-04, 1.94171432e-03, 3.88342863e-03,
        5.00306460e-04, 1.00061292e-03, 2.00122584e-03, 4.00245168e-03,
        4.87580185e-04, 9.75160371e-04, 1.95032074e-03, 3.90064148e-03],
       [3.85310659e-04, 7.70621318e-04, 1.54124264e-03, 3.08248527e-03,
        1.55947281e-04, 3.11894563e-04, 6.23789126e-04, 1.24757825e-03,
        1.39766094e-04, 2.79532189e-04, 5.59064377e-04, 1.11812875e-03,
        2.45623762e-04, 4.91247524e-04, 9.82495048e-04, 1.96499010e-03,
        1.61213094e-04, 3.22426187e-04, 6.44852374e-04, 1.28970475e-03,
        3.68925056e-03, 7.37850112e-03, 1.47570022e-02, 2.95140045e-02,
        1.14244846e-03, 2.28489693e-03, 4.56979386e-03, 9.13958772e-03],
       [1.97849082e-04, 3.95698165e-04, 7.91396330e-04, 1.58279266e-03,
        1.45375163e-04, 2.90750327e-04, 5.81500653e-04, 1.16300131e-03,
        1.86861395e-04, 3.73722791e-04, 7.47445581e-04, 1.49489116e-03,
        5.33589978e-04, 1.06717996e-03, 2.13435991e-03, 4.26871983e-03,
        2.53153863e-04, 5.06307726e-04, 1.01261545e-03, 2.02523091e-03,
        2.56481376e-04, 5.12962753e-04, 1.02592551e-03, 2.05185101e-03,
        6.29101440e-04, 1.25820288e-03, 2.51640576e-03, 5.03281152e-03],
       [4.35396941e-04, 8.70793881e-04, 1.74158776e-03, 3.48317553e-03,
        2.44121485e-03, 4.88242969e-03, 9.76485939e-03, 1.95297188e-02,
        2.93786900e-03, 5.87573801e-03, 1.17514760e-02, 2.35029520e-02,
        2.93812494e-03, 5.87624987e-03, 1.17524997e-02, 2.35049995e-02,
        7.07584736e-03, 1.41516947e-02, 2.83033894e-02, 5.66067788e-02,
        4.36953109e-04, 8.73906218e-04, 1.74781244e-03, 3.49562487e-03,
        5.23479442e-03, 1.04695888e-02, 2.09391777e-02, 4.18783553e-02],
       [3.67702018e-04, 7.35404036e-04, 1.47080807e-03, 2.94161614e-03,
        2.31989985e-04, 4.63979969e-04, 9.27959939e-04, 1.85591988e-03,
        2.01364849e-04, 4.02729699e-04, 8.05459398e-04, 1.61091880e-03,
        2.73825401e-04, 5.47650801e-04, 1.09530160e-03, 2.19060320e-03,
        2.15138022e-04, 4.30276044e-04, 8.60552089e-04, 1.72110418e-03,
        7.00941535e-04, 1.40188307e-03, 2.80376614e-03, 5.60753228e-03,
        5.29406204e-04, 1.05881241e-03, 2.11762482e-03, 4.23524964e-03],
       [2.37402893e-03, 4.74805786e-03, 9.49611572e-03, 1.89922314e-02,
        1.74322518e-03, 3.48645036e-03, 6.97290073e-03, 1.39458015e-02,
        1.07626528e-03, 2.15253056e-03, 4.30506112e-03, 8.61012223e-03,
        3.17261827e-03, 6.34523655e-03, 1.26904731e-02, 2.53809462e-02,
        1.09864964e-03, 2.19729928e-03, 4.39459856e-03, 8.78919713e-03,
        1.11634488e-03, 2.23268975e-03, 4.46537951e-03, 8.93075901e-03,
        4.66060648e-03, 9.32121296e-03, 1.86424259e-02, 3.72848518e-02],
       [1.37460351e-02, 2.74920701e-02, 5.49841402e-02, 1.09968280e-01,
        3.73957731e-02, 7.47915461e-02, 1.49583092e-01, 2.99166184e-01,
        6.54913609e-02, 1.30982722e-01, 2.61965444e-01, 5.23930887e-01,
        2.06592757e-02, 4.13185514e-02, 8.26371029e-02, 1.65274206e-01,
        1.00012751e-01, 2.00025503e-01, 4.00051005e-01, 8.00102010e-01,
        6.33160447e-03, 1.26632089e-02, 2.53264179e-02, 5.06528358e-02,
        3.29310031e-02, 6.58620062e-02, 1.31724012e-01, 2.63448025e-01],
       [2.63369628e-03, 5.26739256e-03, 1.05347851e-02, 2.10695703e-02,
        1.84193834e-03, 3.68387668e-03, 7.36775337e-03, 1.47355067e-02,
        1.60496668e-03, 3.20993335e-03, 6.41986671e-03, 1.28397334e-02,
        5.88194608e-03, 1.17638922e-02, 2.35277843e-02, 4.70555686e-02,
        2.04284267e-03, 4.08568534e-03, 8.17137069e-03, 1.63427414e-02,
        2.23269723e-03, 4.46539447e-03, 8.93078893e-03, 1.78615779e-02,
        3.53348223e-03, 7.06696446e-03, 1.41339289e-02, 2.82678579e-02],
       [1.94262457e-04, 3.88524914e-04, 7.77049828e-04, 1.55409966e-03,
        4.48712147e-04, 8.97424294e-04, 1.79484859e-03, 3.58969717e-03,
        2.53473258e-04, 5.06946517e-04, 1.01389303e-03, 2.02778607e-03,
        7.70609525e-04, 1.54121905e-03, 3.08243810e-03, 6.16487620e-03,
        2.55686950e-04, 5.11373900e-04, 1.02274780e-03, 2.04549560e-03,
        3.88540159e-04, 7.77080318e-04, 1.55416064e-03, 3.10832127e-03,
        7.70203814e-04, 1.54040763e-03, 3.08081526e-03, 6.16163051e-03],
       [1.32613676e-03, 2.65227352e-03, 5.30454704e-03, 1.06090941e-02,
        2.00752692e-03, 4.01505385e-03, 8.03010770e-03, 1.60602154e-02,
        1.46963581e-03, 2.93927161e-03, 5.87854322e-03, 1.17570864e-02,
        3.23582757e-03, 6.47165513e-03, 1.29433103e-02, 2.58866205e-02,
        1.86381470e-03, 3.72762941e-03, 7.45525882e-03, 1.49105176e-02,
        1.21663556e-03, 2.43327112e-03, 4.86654223e-03, 9.73308446e-03,
        2.26476746e-03, 4.52953492e-03, 9.05906984e-03, 1.81181397e-02],
       [2.36163327e-02, 4.72326654e-02, 9.44653309e-02, 1.88930662e-01,
        2.04269637e-02, 4.08539274e-02, 8.17078549e-02, 1.63415710e-01,
        2.75932104e-02, 5.51864209e-02, 1.10372842e-01, 2.20745684e-01,
        9.15182357e-03, 1.83036471e-02, 3.66072943e-02, 7.32145886e-02,
        3.08254217e-02, 6.16508434e-02, 1.23301687e-01, 2.46603374e-01,
        8.66529576e-03, 1.73305915e-02, 3.46611830e-02, 6.93223661e-02,
        1.13163915e-02, 2.26327831e-02, 4.52655661e-02, 9.05311323e-02],
       [4.67215962e-05, 9.34431924e-05, 1.86886385e-04, 3.73772770e-04,
        1.09466886e-04, 2.18933772e-04, 4.37867544e-04, 8.75735088e-04,
        1.14973466e-04, 2.29946932e-04, 4.59893864e-04, 9.19787728e-04,
        8.20324813e-04, 1.64064963e-03, 3.28129925e-03, 6.56259851e-03,
        2.39785329e-04, 4.79570657e-04, 9.59141314e-04, 1.91828263e-03,
        1.54792459e-04, 3.09584919e-04, 6.19169837e-04, 1.23833967e-03,
        1.19582137e-03, 2.39164273e-03, 4.78328546e-03, 9.56657092e-03],
       [8.80462918e+00, 1.76092584e+01, 3.52185167e+01, 7.04370334e+01,
        4.49700029e+00, 8.99400058e+00, 1.79880012e+01, 3.59760023e+01,
        2.59070953e+00, 5.18141905e+00, 1.03628381e+01, 2.07256762e+01,
        5.48644173e+00, 1.09728835e+01, 2.19457669e+01, 4.38915338e+01,
        2.59278281e+00, 5.18556563e+00, 1.03711313e+01, 2.07422625e+01,
        1.05671297e+01, 2.11342594e+01, 4.22685188e+01, 8.45370376e+01,
        3.39985706e+00, 6.79971411e+00, 1.35994282e+01, 2.71988564e+01],
       [8.66941572e-02, 1.73388314e-01, 3.46776629e-01, 6.93553257e-01,
        9.88748181e-02, 1.97749636e-01, 3.95499272e-01, 7.90998544e-01,
        8.52887434e-02, 1.70577487e-01, 3.41154974e-01, 6.82309948e-01,
        8.01775042e-02, 1.60355008e-01, 3.20710017e-01, 6.41420034e-01,
        8.58178562e-02, 1.71635712e-01, 3.43271425e-01, 6.86542850e-01,
        7.25247170e-02, 1.45049434e-01, 2.90098868e-01, 5.80197736e-01,
        8.77432348e-02, 1.75486470e-01, 3.50972939e-01, 7.01945878e-01],
       [8.83144200e-03, 1.76628840e-02, 3.53257680e-02, 7.06515360e-02,
        8.59743856e-03, 1.71948771e-02, 3.43897543e-02, 6.87795085e-02,
        8.91610568e-03, 1.78322114e-02, 3.56644227e-02, 7.13288454e-02,
        1.34456617e-02, 2.68913234e-02, 5.37826468e-02, 1.07565294e-01,
        1.87859716e-02, 3.75719432e-02, 7.51438863e-02, 1.50287773e-01,
        8.34481756e-03, 1.66896351e-02, 3.33792702e-02, 6.67585404e-02,
        1.00134379e-02, 2.00268757e-02, 4.00537514e-02, 8.01075029e-02],
       [2.89311913e-01, 5.78623826e-01, 1.15724765e+00, 2.31449530e+00,
        4.01254121e-01, 8.02508242e-01, 1.60501648e+00, 3.21003297e+00,
        4.80965236e-01, 9.61930473e-01, 1.92386095e+00, 3.84772189e+00,
        7.76838240e-01, 1.55367648e+00, 3.10735296e+00, 6.21470592e+00,
        9.70750087e-01, 1.94150017e+00, 3.88300035e+00, 7.76600070e+00,
        2.56650557e-01, 5.13301114e-01, 1.02660223e+00, 2.05320446e+00,
        4.97147067e-01, 9.94294133e-01, 1.98858827e+00, 3.97717653e+00],
       [3.29025303e-01, 6.58050605e-01, 1.31610121e+00, 2.63220242e+00,
        6.60228083e-01, 1.32045617e+00, 2.64091233e+00, 5.28182467e+00,
        6.82736105e-01, 1.36547221e+00, 2.73094442e+00, 5.46188884e+00,
        3.84676291e-01, 7.69352582e-01, 1.53870516e+00, 3.07741033e+00,
        6.24030574e-01, 1.24806115e+00, 2.49612230e+00, 4.99224459e+00,
        2.22792590e-01, 4.45585180e-01, 8.91170360e-01, 1.78234072e+00,
        7.80754866e-01, 1.56150973e+00, 3.12301946e+00, 6.24603892e+00],
       [1.76334690e-03, 3.52669380e-03, 7.05338760e-03, 1.41067752e-02,
        1.21314048e-02, 2.42628097e-02, 4.85256193e-02, 9.70512386e-02,
        8.77260194e-03, 1.75452039e-02, 3.50904078e-02, 7.01808156e-02,
        1.70266626e-02, 3.40533253e-02, 6.81066505e-02, 1.36213301e-01,
        1.29494546e-02, 2.58989093e-02, 5.17978186e-02, 1.03595637e-01,
        5.44196716e-03, 1.08839343e-02, 2.17678686e-02, 4.35357373e-02,
        1.90328914e-02, 3.80657828e-02, 7.61315655e-02, 1.52263131e-01],
       [3.00000000e+00, 6.00000000e+00, 1.20000000e+01, 2.40000000e+01,
        6.84615385e+00, 1.36923077e+01, 2.73846154e+01, 5.47692308e+01,
        5.76923077e+00, 1.15384615e+01, 2.30769231e+01, 4.61538462e+01,
        6.17142857e+00, 1.23428571e+01, 2.46857143e+01, 4.93714286e+01,
        1.11785714e+01, 2.23571429e+01, 4.47142857e+01, 8.94285714e+01,
        3.27083333e+00, 6.54166667e+00, 1.30833333e+01, 2.61666667e+01,
        3.92553191e+00, 7.85106383e+00, 1.57021277e+01, 3.14042553e+01]])

In [43]:
processInfos_x.var()

Na+      7.905212e+01
NH4+     1.055624e+01
K+       2.232880e+00
Mg2+     3.008136e-02
Ca2+     2.475103e+00
F-       8.975281e-03
Cl-      3.315984e+01
NO3-     3.336025e+02
SO42-    2.518012e+02
Li       2.035762e-06
Be       5.886663e-12
Ti       2.024295e-06
V        3.740529e-05
Cr       1.407174e-06
Mn       1.806201e-04
Ni       1.643013e-06
Cu       6.960894e-05
Zn       3.210871e-02
As       1.013379e-04
Cd       3.817643e-08
Sn       2.546949e-06
Sb       3.641407e-05
Ba       4.207004e-03
Hg       8.879592e-10
Tl       9.587661e-08
Pb       4.822332e-06
Na       4.043219e+02
Mg       5.543993e-02
Al       1.181953e-03
K        3.335609e+00
Ca       2.907846e+00
Fe       1.619602e-03
WSOC     3.961085e+02
dtype: float64

In [44]:
mask = thresholder.get_support()
ansure_infos = processInfos_x.loc[:, mask]
ansure_infos.head(2)

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Sb,Ba,Pb,Na,Mg,Al,K,Ca,Fe,WSOC
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.001326,0.023616,0.000047,8.804629,0.086694,0.008831,0.289312,0.329025,0.001763,3.0
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.002652,0.047233,0.000093,17.609258,0.173388,0.017663,0.578624,0.658051,0.003527,6.0

In [45]:
selection_x = processInfos_x[indexs[:9]]
selection_x.head(2)

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22

In [86]:
###创建相关矩阵
import numpy as np

corr_matrix = processInfos_x.corr().abs()

In [87]:
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(np.bool))

/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.

In [89]:
upper.to_csv("./data/corr_matrix.csv")

In [124]:
import pandas as pd

In [47]:
infos_path = "./data/sub_data/cycle_defeat_infos.xlsx"
infos = pd.read_excel(infos_path)
index_names = infos.columns.to_list()
indexs = index_names[1:35]
indexs.remove("Co")

In [48]:
processInfos_x = infos[indexs]
Infos_target = infos["label"]
processInfos_x.head(2)

,Na+,NH4+,K+,Mg2+,Ca2+,F-,Cl-,NO3-,SO42-,Li,...,Hg,Tl,Pb,Na,Mg,Al,K,Ca,Fe,WSOC
0,3.992286,0.239333,0.258167,0.052429,0.260310,0.015095,0.663262,1.876357,6.11,0.000503,...,0.000007,0.0,0.000047,8.804629,0.086694,0.008831,0.289312,0.329025,0.001763,3.0
1,7.984571,0.478667,0.516333,0.104857,0.520619,0.030190,1.326524,3.752714,12.22,0.001005,...,0.000014,0.0,0.000093,17.609258,0.173388,0.017663,0.578624,0.658051,0.003527,6.0

In [185]:
Infos_target

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    2
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
Name: label, dtype: int64

In [49]:
##计算每一个特征与目标向量之间的方差分析F值
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [50]:
fv, pv = f_classif(processInfos_x, Infos_target)
f_infos = {"features":indexs,"F_values":fv,"P_values":pv}
f_df = pd.DataFrame(f_infos)
f_df.head(2)

  features  F_values  P_values
0      Na+  1.750441  0.197340
1     NH4+  4.014416  0.055637

In [188]:
f_df.to_csv("./data/循环缺失ANOVA_res.csv")

In [222]:
### 构建模型---logisticRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
scaler = StandardScaler()
feature_standardized = scaler.fit_transform(processInfos_x)
logistic_regression = LogisticRegression(random_state=0,multi_class="ovr",class_weight="balanced")
model = logistic_regression.fit(feature_standardized,Infos_target)
pred_y = model.predict(feature_standardized)
pred_y
# accuracy = accuracy_score(Infos_target,pred_y)
# accuracy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [223]:
kfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=0)
results = cross_val_score(logistic_regression, feature_standardized, Infos_target, cv=kfold)

/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/sklearn/model_selection/_split.py:668: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  % (min_groups, self.n_splits)), UserWarning)
/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/sklearn/model_selection/_validation.py:619: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/snn/anaconda3/envs/drugex/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py", line 1376, in fit
    " class: %r" % classes_[0])
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

  FitFailedWarning)

In [224]:
results

array([1.        , 1.        , 1.        , 1.        , 0.66666667,
       1.        , 1.        ,        nan, 1.        , 1.        ])